spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_database?useSSL=false&serverTimezone=UTC
    username: root
    password: #put the password here
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    database: MYSQL

server:
  port: 8082


logging:
  level:
    org: DEBUG
