spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: products-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**    -
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
server:
  port: 8090
